/**
 * Single source of content for the /variants home explorations.
 * Facts mirror the live home, the case studies, and the CV — keep them in sync
 * rather than inventing new claims per variant.
 */

export type CaseStudySlug = "domis" | "virdio" | "obscura" | "memory-care";

export interface VariantMedia {
  src: string;
  alt: string;
  /** Intrinsic size, used for next/image aspect ratio. */
  w: number;
  h: number;
  /** Looping muted video; `src` is its poster. */
  video?: string;
  caption?: string;
}

export interface VariantProject {
  slug: CaseStudySlug;
  href: string;
  name: string;
  /** Who it was for / where it lives. */
  org: string;
  role: string;
  years: string;
  medium: string;
  /** The homepage sentence. */
  title: string;
  summary: string;
  outcome: { value: string; label: string };
  /** Brand colour from the live home cards. */
  color: string;
  /** Readable text colour on `color`. */
  onColor: string;
  cover: VariantMedia;
  gallery: VariantMedia[];
}

export const PROJECTS: VariantProject[] = [
  {
    slug: "domis",
    href: "/domis",
    name: "Domis",
    org: "Domis",
    role: "Founding Product Designer",
    years: "2024 – Now",
    medium: "iOS · AI · 0 to 1",
    title: "A home maintenance app that learns your home as you use it",
    summary:
      "Building Domis from zero, including how it learns a house from an address, a photo, and an inspection report. Making the most of the smallest action a user will take.",
    outcome: { value: "60%", label: "lift in new-user engagement from the 3D home avatar" },
    color: "#ff5a5b",
    onColor: "#ffffff",
    cover: {
      src: "/assets/home/domis-card1-tasks-composite.png",
      alt: "Domis turning an inspection report into a list of tasks",
      w: 470,
      h: 700,
      video: "/assets/home/domis-card2-anim.mp4",
      caption: "Domis turns messy documents into actionable items for your home",
    },
    gallery: [
      {
        src: "/assets/domis/hero-mobile.png",
        alt: "Domis home screen on iPhone",
        w: 473,
        h: 1024,
        caption: "Designed to log every detail while feeling light",
      },
      {
        src: "/assets/domis/live/home-avatar-3d.png",
        alt: "A 3D avatar of a house generated by Domis",
        w: 512,
        h: 512,
        caption: "A personalized 3D avatar of your home, from one photo",
      },
      {
        src: "/assets/home/domis-card1-tasks-composite.png",
        alt: "Inspection report becoming tasks in Domis",
        w: 470,
        h: 700,
        caption: "A messy inspection PDF becomes a list of tasks",
      },
    ],
  },
  {
    slug: "virdio",
    href: "/virdio",
    name: "Virdio",
    org: "Virdio",
    role: "Product Designer",
    years: "2021 – 2022",
    medium: "AR · iOS · Android · Web · TV",
    title: "An AR fitness platform across every screen",
    summary:
      "Turning Virdio’s machine vision-based AR technology into a consumer facing fitness platform via lightweight mobile and desktop apps.",
    outcome: { value: "50%", label: "less handoff time with a token system across four platforms" },
    color: "#171528",
    onColor: "#ece8ff",
    cover: {
      src: "/assets/home/virdio-ar-desktop.webp",
      alt: "Virdio AR workout running on a desktop",
      w: 980,
      h: 549,
      video: "/assets/home/virdio-hero-crop.mp4",
      caption: "Machine-vision overlays turned into a consumer workout",
    },
    gallery: [
      {
        src: "/assets/virdio/in_context.png",
        alt: "Virdio AR workout in a living room",
        w: 2066,
        h: 1096,
        caption: "AR fitness for any space, no hardware",
      },
      {
        src: "/assets/virdio/hero_ui.png",
        alt: "Virdio workout telemetry overlay",
        w: 1402,
        h: 786,
        caption: "High-contrast telemetry you can read mid-squat",
      },
      {
        src: "/assets/virdio/sketch_setup.jpg",
        alt: "Sketch of the Virdio camera setup",
        w: 1144,
        h: 1000,
        caption: "Making calibration feel like a warm-up, not a scan",
      },
    ],
  },
  {
    slug: "obscura",
    href: "/obscura",
    name: "OBSCURA",
    org: "MOHAI, Seattle",
    role: "Interaction Design · Unity Dev",
    years: "2024 – 2025",
    medium: "VR · Immersive exhibit",
    title: "A photographic exhibit where your gaze tells the story",
    summary:
      "Taking 300+ unseen photos from WW2 and turning them into a VR-driven immersive experience for the visitors at the Museum of History and Industry.",
    outcome: { value: "300+", label: "unseen photographs, curated live by where you look" },
    color: "#111111",
    onColor: "#f4f4f3",
    cover: {
      src: "/assets/home/obscura-sbs-view.webp",
      alt: "OBSCURA headset view beside the audience view",
      w: 980,
      h: 520,
      video: "/assets/home/obscura-sbs-video.mp4",
      caption: "An asynchronous VR exhibit hosted at MOHAI",
    },
    gallery: [
      {
        src: "/assets/obscura/wayne_crowd_scene.jpg",
        alt: "Archival photograph of a crowd in post-war Japan",
        w: 2400,
        h: 2304,
        caption: "From an archive of 300+ photographs never shown before",
      },
      {
        src: "/assets/obscura/exhibition_743gm1tgvfizndo7gwveqtjp584.webp",
        alt: "OBSCURA exhibition vitrine at MOHAI",
        w: 1024,
        h: 768,
        caption: "Exhibited 13 September 2025 to a full audience",
      },
      {
        src: "/assets/obscura/spectatorIMG.png",
        alt: "A spectator watching the shared audience display",
        w: 1620,
        h: 1712,
        caption: "One visitor’s gaze becomes everyone’s story",
      },
    ],
  },
  {
    slug: "memory-care",
    href: "/memory-care",
    name: "Memory Care",
    org: "SF Campus for Jewish Living",
    role: "Interaction Designer",
    years: "2020 – 2023",
    medium: "Tangible · Healthcare",
    title: "Enriching experiences for people living with Alzheimer’s",
    summary:
      "R&D for the MCES, a multi-modal interactive installation by Maria Mortati aiming to provide life enrichment for people living with mid-to-late stage dementia.",
    outcome: { value: "98%", label: "positive evaluations across 200+ test sessions" },
    color: "#ff9f73",
    onColor: "#2b2a27",
    cover: {
      src: "/assets/memory-care/station_full.jpg",
      alt: "The Memory Care Experience Station with a driving simulator",
      w: 2400,
      h: 1800,
      caption: "The MCES lives at the SFCJL in San Francisco",
    },
    gallery: [
      {
        src: "/assets/memory-care/cathero.png",
        alt: "Residents petting the haptic cat simulator",
        w: 2073,
        h: 1181,
        caption: "I built interactives like the haptic cat petting simulator",
      },
      {
        src: "/assets/memory-care/cat_arduino_wiring.jpg",
        alt: "Arduino wiring inside the haptic cat prototype",
        w: 2400,
        h: 1800,
        caption: "Sensors, an Arduino, and a lot of tape",
      },
      {
        src: "/assets/home/mces-library-dashboard.png",
        alt: "Digital library dashboard for caregivers",
        w: 1440,
        h: 800,
        caption: "A digital library caregivers can run a session from",
      },
    ],
  },
];

export const RECOGNITION = [
  { label: "Fast Company World Changing Ideas", detail: "Finalist, 2022 · Memory Care" },
  { label: "CABHI", detail: "2× award recipient · Memory Care" },
  { label: "SCAN Foundation Innovation Award", detail: "Memory Care" },
  { label: "OBSCURA at MOHAI", detail: "Sold out · 13 Sep 2025" },
] as const;

export interface VariantWaffling {
  slug: string;
  href: string;
  name: string;
  line: string;
  media: VariantMedia;
}

export const WAFFLINGS: VariantWaffling[] = [
  {
    slug: "savor",
    href: "/waffling/savor",
    name: "Savor",
    line: "A phone video in, a 3D Gaussian splat out. Mac-native, no cloud.",
    media: {
      src: "/assets/savor/hero-poster.jpg",
      alt: "Rodin’s Mighty Hand captured as a 3D Gaussian splat",
      w: 1280,
      h: 720,
    },
  },
  {
    slug: "orca",
    href: "/waffling/orca",
    name: "Saving Baby J",
    line: "An arcade game you play by throwing orca plushies at the screen.",
    media: {
      src: "/assets/orca/card.jpg",
      alt: "Saving Baby J arcade game title screen",
      w: 759,
      h: 900,
    },
  },
  {
    slug: "recorder",
    href: "/waffling/recorder",
    name: "Recorder-Proto",
    line: "A skeuomorphic voice recorder with a turntable scrub.",
    media: {
      src: "/assets/recorder/card.png",
      alt: "Recorder prototype with a turntable dial",
      w: 390,
      h: 470,
    },
  },
  {
    slug: "butter-chicken",
    href: "/butter-chicken",
    name: "Butter Chicken",
    line: "A vibes-based recipe. Taste scales linearly with butter.",
    media: {
      src: "/assets/butter-chicken/hero.jpg",
      alt: "A pan of butter chicken",
      w: 797,
      h: 733,
    },
  },
];

export const BIO = {
  name: "Hridae Walia",
  role: "Product Designer",
  location: "San Francisco",
  now: "Founding Product Designer at Domis",
  thesis: "Designing for interaction models that barely exist yet.",
  long: "I’m a Product Designer obsessed with making, and I have 6 years of experience designing for interaction models that barely exist yet. I focus on the user and learn by making, whether on the canvas, in code, or the physical world.",
  education: [
    "MHCI+D, University of Washington",
    "BFA Interaction Design, California College of the Arts",
  ],
} as const;

export const TOOLKIT = [
  { name: "Pencil", file: "pencil.webp" },
  { name: "Paper", file: "paper.webp" },
  { name: "Figma", file: "figma.webp" },
  { name: "Cursor", file: "cursor.webp" },
  { name: "Claude Code", file: "claude.webp" },
  { name: "Xcode", file: "xcode.webp" },
  { name: "Origami", file: "origami.webp" },
  { name: "ProtoPie", file: "protopie.webp" },
] as const;

export function toolIconSrc(file: string) {
  return `/tool-icons/light/fill/${encodeURIComponent(file)}`;
}

export function projectBySlug(slug: CaseStudySlug): VariantProject {
  const p = PROJECTS.find((x) => x.slug === slug);
  if (!p) throw new Error(`Unknown project ${slug}`);
  return p;
}
