/** Auto-generated by scripts/build-sketch-orbs.mjs — run after adding sketches to source folder. */
export const SKETCH_ORB_IMAGES = [
  "/assets/home/sketch-orbs/sketch-01.webp",
  "/assets/home/sketch-orbs/sketch-02.webp",
  "/assets/home/sketch-orbs/sketch-03.webp",
  "/assets/home/sketch-orbs/sketch-04.webp",
  "/assets/home/sketch-orbs/sketch-05.webp",
  "/assets/home/sketch-orbs/sketch-06.webp",
  "/assets/home/sketch-orbs/sketch-07.webp",
  "/assets/home/sketch-orbs/sketch-08.webp",
  "/assets/home/sketch-orbs/sketch-09.webp",
  "/assets/home/sketch-orbs/sketch-10.webp",
  "/assets/home/sketch-orbs/sketch-11.webp",
  "/assets/home/sketch-orbs/sketch-12.webp",
] as const;

export type SketchOrbImageUrl = (typeof SKETCH_ORB_IMAGES)[number];
